### ISSUE TITLE
Events and sleep

### ISSUE THREAD

**Issue by MayankKharbanda** [MayankKharbanda/GetBlock#19]
@samyakahuja I have added events in the program, see if it's good.

**Comment by samyakahuja** [comment]
@MayankKharbanda 
Ok, so you have added `MAX_BLOCKS + 1` events, and a process waits for the event to be set if it doesn't get a buffer. Then when the buffer is freed then all the processes waiting on that block or any block are woken up and all of them again put in a request. 

I have two problems with this - 
+ A process has to put in a request at the end of the request_queue - which can't really be avoided since that is how we implemented our system - which I think defeats the purpose of sleeping on an event.
A process waiting on a block should immediately get hold of the buffer that contained it and was just released because that way a new block isn't read into that buffer and it saves on disk I/O.

+ With your implementation if x processess are waiting on an event then all of them are woken up and all of them put in a fresh request. Maybe you should consider using [Condition Variables](https://docs.python.org/3/library/threading.html#threading.Condition). I am not exactly sure how that works, give it look. Maybe events are enought for our purpose. I am saying it again, I don't know and will have to look it in detail.

All in all, good job. But chain nahi hai tujhe bro! Aaj hi bola maam ne aur tune aaj hi implement kar diya 😅

**Comment by MayankKharbanda** [comment]
@samyakahuja 
For first problem I was thinking it to be inefficient, to clear the whole queue and then refill it, maybe discuss with mam in next lecture.
For the second one, I think this would also work good, and we could try Condition Variables, but I didn't found anywhere, is notify function call one thread randomly, or the first one waiting?

I thought kaam nipta do ab thode bahut ke liye latkaao mat.

**Comment by samyakahuja** [comment]
@MayankKharbanda 
I think I may have found a solution to our problem
Take a look at [Priority Queues](https://docs.python.org/3/library/queue.html#queue.PriorityQueue).

With this, we can just increase the priority of the thread waking from sleep after an event like buffer became free.

**Comment by MayankKharbanda** [comment]
@samyakahuja 
But that would be a disadvantage for the threads which already requested for getblock but not implemented the algorithm yet.
